Inventory/Inventory/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', login, name='login'),
    #url(r'^login/$', auth_views.login, name='login'),
    #url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^logout/$', logout, {'next_page': '/'}),
    url(r'^', include('items.urls')),
]

Inventory/items/urls.py
from django.conf.urls import url, include
from  . import views
from django.contrib.auth.views import login
from account.views import *

urlpatterns = [
    url(r'^$', views.index, name='index'),
    #url(r'^details/(?P<id>\w{0,50})/$', views.details)
    url(r'add', views.add, name='add'),
    url(r'(?P<pk>[0-9]+)/delete', views.delete, name='delete'),
    url(r'(?P<pk>[0-9]+)/edit', views.edit, name='edit'),
    url(r'(?P<pk>[0-9]+)/increment', views.increment, name='increment'),
    url(r'(?P<pk>[0-9]+)/decrement', views.decrement, name='decrement'),
    url(r'^login/', login),
]

Inventory/account/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

Inventory/items/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.utils import timezone
from django.db import models

# Create your models here.
class Items(models.Model):
	title = models.CharField(max_length=100)
	quantity = models.PositiveSmallIntegerField(default=1)
	unit = models.CharField(max_length=50, default='units')
	category = models.CharField(max_length=100, default='Others')
	created_at = models.DateField(default=timezone.now(), blank=True)
	expires_at = models.DateField(null=True, blank=True)
	
	def __str__(self):
		return self.title

Inventory/account/forms.py
import re
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
 
class RegistrationForm(forms.Form):
 
    username = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Username"), error_messages={ 'invalid': _("This value must contain only letters, numbers and underscores.") })
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Email address"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password (again)"))
 
    def clean_username(self):
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("The username already exists. Please try another one."))
 
    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields did not match."))
        return self.cleaned_data

Inventory/account/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
#views.py
from account.forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.template import RequestContext
 
@csrf_protect
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password1'],
            email=form.cleaned_data['email']
            )
            return HttpResponseRedirect('/register/success/')
    else:
        form = RegistrationForm()
    variables = RequestContext(request, {
    'form': form
    })
 
    return render_to_response(
    'registration/register.html',
    variables,
    )
 
def register_success(request):
    return render_to_response(
    'registration/success.html',
    )
 
def logout_page(request):
    logout(request)
    return HttpResponseRedirect('items/login/')

Inventory/items/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Items

# Create your views here.
@login_required(login_url='/login')
def index(request):
	items = Items.objects.all()

	context = {'items': items}
	return render(request, 'index.html', context)

@login_required(login_url='/login')
def add(request):
	if(request.method == 'POST'):
		title = request.POST['title'].strip()
		quantity = request.POST['quantity']
		unit = request.POST['unit']
		category = request.POST['category']
		created = request.POST['created_at']
		expires = request.POST['expires_at']
		
		if Items.objects.filter(title=title).exists():
			messages.error(request, "Error: Item name already exist")
		else:
			if (expires == '' or expires == 'None'):
				item = Items(title=title, quantity=quantity, unit=unit, category=category, created_at=created)
			else:
				item = Items(title=title, quantity=quantity, unit=unit, category=category, created_at=created, expires_at=expires)
			item.save()

		return redirect('/')
	else:
		return render(request, 'add.html')

@login_required(login_url='/login')
def edit(request, pk):
	if(request.method == 'POST'):
		quantity = request.POST['quantity']
		category = request.POST['category']
		expires = request.POST['expires_at']

		if (expires == '' or expires == 'None'):
			Items.objects.filter(pk=pk).update(quantity=quantity)
			Items.objects.filter(pk=pk).update(category=category)
		else:
			Items.objects.filter(pk=pk).update(quantity=quantity)
			Items.objects.filter(pk=pk).update(category=category)
			Items.objects.filter(pk=pk).update(expires_at=expires)
		#item.save()

		return redirect('/')
	else:
		item = Items.objects.get(id=pk)

		context = {'item': item}
		return render(request, 'edit.html', context)

@login_required(login_url='/login')
def increment(request, pk):
	i = 1 + Items.objects.values_list('quantity', flat=True).get(pk=pk)
	Items.objects.filter(pk=pk).update(quantity=i)
	return redirect('/')

@login_required(login_url='/login')
def decrement(request, pk):
	i = Items.objects.values_list('quantity', flat=True).get(pk=pk) - 1
	if (i > 0):
		Items.objects.filter(pk=pk).update(quantity=i)
	return redirect('/')

@login_required(login_url='/login')
def delete(request, pk):
	Items.objects.filter(id=pk).delete()
	return redirect('/')

Inventory/items/templates/add.html
{% include 'partials/header.html' %}
	<div class="add_form">
		<form action="{% url 'add' %}" method="post">
			{% csrf_token %}
			<label for="title">Name</label><br>
			<input type="text" name="title" id="title" placeholder="Enter item name here" required/>
			<br>
			<label class="required" for="id_quantity">Quantity</label><br>
			<input type="number" name="quantity" value="1" id="id_quantity" required class="vIntegerField" min="1" />
			<br>
			<label for="unit">Unit</label><br>
			<select name="unit" id="unit">
				<option value="u">u</option>
				<option value="g">g</option>
				<option value="kg">kg</option>
				<option value="ml">ml</option>
				<option value="packets">packets</option>
				<option value="bottles">bottles</option>
			</select>
			<br>
			<label for="category">Category</label><br>
			<select name="category" id="category">
				<option value="Fruits">Fruits</option>
				<option value="Vegetables">Vegetables</option>
				<option value="Drinks">Drinks</option>
				<option value="Meat">Meat</option>
				<option value="Snacks">Snacks</option>
			</select>
			<br>
			<label for="id_created_at">Created at</label><br>
			<input type="date" name="created_at" id="id_created_at" size="10" required />
			<br>
			<label for="id_expires_at">Expires at</label><br>
			<input type="date" name="expires_at" id="id_expires_at" size="10" />
			<br><br>
			<input class="btn btn-primary" type="submit" value="Add" />
		</form>
		{% if messages %}
		<ul class="messages">
			{% for message in messages %}
			<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
		</ul>
		{% endif %}
		<br>
		<a href="/">Go Back</a>
	</div>
	<div class="container">
	  <form>
	    <div class="form-group row">
	      <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
	      <div class="col-sm-10">
	        <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
	      </div>
	    </div>
	    <div class="form-group row">
	      <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
	      <div class="col-sm-10">
	        <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
	      </div>
	    </div>
	    <fieldset class="form-group">
	      <div class="row">
	        <legend class="col-form-legend col-sm-2">Radios</legend>
	        <div class="col-sm-10">
	          <div class="form-check">
	            <label class="form-check-label">
	              <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="option1" checked>
	              Option one is this and that&mdash;be sure to include why it's great
	            </label>
	          </div>
	          <div class="form-check">
	            <label class="form-check-label">
	              <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios2" value="option2">
	              Option two can be something else and selecting it will deselect option one
	            </label>
	          </div>
	          <div class="form-check disabled">
	            <label class="form-check-label">
	              <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios3" value="option3" disabled>
	              Option three is disabled
	            </label>
	          </div>
	        </div>
	      </div>
	    </fieldset>
	    <div class="form-group row">
	      <div class="col-sm-2">Checkbox</div>
	      <div class="col-sm-10">
	        <div class="form-check">
	          <label class="form-check-label">
	            <input class="form-check-input" type="checkbox"> Check me out
	          </label>
	        </div>
	      </div>
	    </div>
	    <div class="form-group row">
	      <div class="col-sm-10">
	        <button type="submit" class="btn btn-primary">Sign in</button>
	      </div>
	    </div>
	  </form>
	</div>
{% include 'partials/footer.html' %}

Inventory/items/templates/base.html
<!-- base.html -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load staticfiles %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href=" {% static 'css/base.css'%}">
    <link rel="stylesheet" type="text/css" href=" {% static 'css/home.css'%}">
</head> 
<body>
    <div class="wrapper">
        <div class="container">
            <h1>{% block head %}{% endblock %}</h1>
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

Inventory/items/templates/edit.html
{% include 'partials/header.html' %}
	<form action="{% url 'edit' item.id %}" method="post">
		{% csrf_token %}
		<label for="title">Name: {{item.title}}</label>
		<br>
		<label class="required" for="id_quantity">Quantity:</label>
		<input type="number" name="quantity" value="{{item.quantity}}" id="id_quantity" required class="vIntegerField" min="1" />
		<br>
		<label for="category">Category:</label>
		<input list="categories" name="category" id="category" placeholder="Choose an category" value="{{item.category}}" required/>
		<datalist id="categories">
			<option value="Fruits">
			<option value="Vegetables">
			<option value="Drinks">
			<option value="Meat">
			<option value="Snacks">
		</datalist>
		<br>
		<label for="id_expires_at">Expires at:</label>
		<input type="date" name="expires_at" id="id_expires_at" size="10" value="{{item.expires_at|date:'Y-m-d'}}" />
		<br><br>
		<input type="submit" value="Submit" />
	</form>
{% include 'partials/footer.html' %}

Inventory/items/templates/index.html
{% include 'partials/header.html' %}
	<body>
		<h1><b>Items</b></h1>
		<p>
			<div class="add_item"><a href="add/">Add Item</a></div>
			<div class="welcome_msg">Welcome {{request.user.username}}<a href="logout/"> Logout</a></div>
		</p>
	</body>

	<table class="table table-bordered" id="items_table">
		<thead>
			<tr>
				<th>Item</th>
				<th>Quantity</th>
				<th>Category</th>
				<th>Bought on</th>
				<th>Expires on</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for item in items %}
			<tr>
				<td>{{item.title}}</td>
				<td>{{item.quantity}}{{item.unit}}
					<a href="{% url 'increment' item.id %}"> + </a>
					<a href="{% url 'decrement' item.id %}"> -- </a></td>
				<td>{{item.category}}</td>
				<td>{{item.created_at|date:"d/m/Y"}}</td>
				<td>{{item.expires_at|date:"d/m/Y"}}</td>
				<td>
					<a href="{% url 'edit' item.id %}">edit</a>
					<a href="{% url 'delete' item.id %}">delete</a>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>

	<div class="add_form">
		<form action="{% url 'add' %}" method="post">
			{% csrf_token %}
			<label for="title">Name</label><br>
			<input type="text" name="title" id="title" placeholder="Enter item name here" required/>
			<br>
			<label class="required" for="id_quantity">Quantity</label><br>
			<input type="number" name="quantity" value="1" id="id_quantity" required class="vIntegerField" min="1" />
			<br>
			<label for="unit">Unit</label><br>
			<select name="unit" id="unit">
				<option value="u">u</option>
				<option value="g">g</option>
				<option value="kg">kg</option>
				<option value="ml">ml</option>
				<option value="packets">packets</option>
				<option value="bottles">bottles</option>
			</select>
			<br>
			<label for="category">Category</label><br>
			<select name="category" id="category">
				<option value="Fruits">Fruits</option>
				<option value="Vegetables">Vegetables</option>
				<option value="Drinks">Drinks</option>
				<option value="Meat">Meat</option>
				<option value="Snacks">Snacks</option>
			</select>
			<br>
			<label for="id_created_at">Created at</label><br>
			<input type="date" name="created_at" id="id_created_at" size="10" required />
			<br>
			<label for="id_expires_at">Expires at</label><br>
			<input type="date" name="expires_at" id="id_expires_at" size="10" />
			<br><br>
			<input class="btn btn-primary" type="submit" value="Add" />
		</form>
		{% if messages %}
		<ul class="messages">
			{% for message in messages %}
			<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
		</ul>
		{% endif %}
	</div>

	<!-- Autofills created at with current date -->
	<script type="text/javascript">
		document.getElementById('id_created_at').valueAsDate = new Date();
	</script>
  	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  	<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
 	<!-- Latest compiled and minified JavaScript -->
 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
 	<script type="text/javascript">
	$(document).ready(function() {
    	$('#items_table').DataTable();
	});
 	</script>
</html>

Inventory/items/templates/partials/footer.html
  	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
 	<!-- Latest compiled and minified JavaScript -->
 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

Inventory/items/templates/partials/header.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="Cache-Control" content="max-age=0" />
		<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
		<link href='https://fonts.googleapis.com/css?family=Bad Script' rel='stylesheet'>
		<meta name="theme-color" content="#ffffff">
		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
		<title>Items in Kitchen</title>
	</head>